### ISSUE TITLE
Offset background

### ISSUE THREAD

**Issue by CcMenta** [luisbocanegra/plasma-panel-colorizer#57]
There are some widgets that have a little space on either side like the default digital clock (at least if you have date disabled) so it would be good if we could offset it just a bit so it looks good.

**Comment by luisbocanegra** [comment]
Sorry I am having trouble to understand what exactly you mean. Is the issue about widgets that have uneven padding and drawing backgrounds on them looks bad so you would like the offset to control each side separately? Or is the problem caused by Panel Colorizer?

Can you please share a screenshot or a quick drawing that illustrates of the problem?

**Comment by CcMenta** [comment]
The first one you said now.
![stuff](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/44743415/dfbaa061-9d47-48f3-a747-5cbb099272bf)

**Comment by luisbocanegra** [comment]
Thanks for the illustration. I will try to add this in a upcoming release

**Comment by luisbocanegra** [comment]
Upcoming version will support configuration overrides, with it it is possible to set custom margins for one or multiple w¿

That will solve this issue.

Check the [v1.0.0 milestone](https://github.com/luisbocanegra/plasma-panel-colorizer/milestone/1) for the current progress
